### ISSUE TITLE
Specifying dependencies at version "*" is a Bad Idea

### ISSUE THREAD

**Issue by cowboy** [backbone-boilerplate/grunt-bbb#119]
When someone requires `bbb@0.2.0` in their project, they have a reasonable expectation (according to SemVer) that no bbb-installed task behaviors will change, ever, period. And when someone requires `bbb@~0.2.0` in their project, they have a reasonable expectation that no backwards-breaking changes will occur, ever, period.

But because bbb [peerDependencies are all specified as version "*"](https://github.com/backbone-boilerplate/grunt-bbb/blob/460ae9e752cca7e34c91579dbe808dc42507ea6d/package.json#L18-L22) like this:

```json
{
  "peerDependencies": {
    "grunt-bbb-server": "*",
    "grunt-bbb-require": "*",
    "grunt-bbb-styles": "*"
  }
}
```

There is only one way for a user of bbb to have either of these guarantees:

**That user will have to specify all of bbb's peerDependencies _additionally, explicitly as devDependencies_, at the specific version(s) whose continued, consistent behavior they wish to utilize.**

Doesn't that defeat the benefit the user of specifying peerDependencies in bbb?

**Comment by tbranyen** [comment]
Deprecated this project.
