### ISSUE TITLE
Specify Grunt as a peerDependency

### ISSUE THREAD

**Issue by cowboy** [backbone-boilerplate/grunt-bbb#120]
It's a good idea, because it guarantees that a minimum required version of Grunt is installed, and it has the added benefit of showing a Grunt version on the website:

http://gruntjs.com/plugins/bbb

This should be done for all grunt-bbb plugins, but I'm just going to file the issue once, here.

**Comment by tbranyen** [comment]
Deprecated this project.

**Comment by SBoudrias** [comment]
Also, FWIW, peerDependencies is also deprecated in npm starting v3.0
